name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        working-directory: ./app
        run: npm install
      - name: Build
        working-directory: ./app
        run: |
          npm run build
          echo "Current directory contents:"
          ls -la
          echo "Parent directory contents:"
          ls -la ../
          echo "Public directory contents:"
          ls -la public/
      - name: Copy well-known files
        working-directory: ./app
        run: |
          echo "Checking if out directory exists:"
          ls -la out/ || mkdir -p out/
          mkdir -p out/.well-known
          cp -r public/.well-known/* out/.well-known/
          echo "Final out directory contents:"
          ls -la out/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./app/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
